### ISSUE TITLE
nested loops

### ISSUE THREAD

**Issue by FunnyDevs** [amoerie/jstreams#11]
Hi! I would like to use your library overall to replace a lot of nested loops. It's convenient? I think i must use a forEach inside another ForEach, with the nested ForEach that everytime creates a new Stream (and so a lot of in memory list vs nested loops with only two in memory list).

**Comment by amoerie** [comment]
Hi.

I do think it's convenient! Almost all traditionally written loops can be replaced with a more functional style approach to collections, which is what JStreams tries to be.

It does have the disadvantage of allocating a lot of objects, but you'll notice that these are all immutable and disappear immediately after they are used, allowing the garbage collector to clean it up rather quickly. 

I'd say the benefit of having less and clearer code, written in a declarative way, is definitely worth the extra allocations. And if you do encounter some performance hotspot, you can always just dial it back a notch and write it with traditional lists and arrays again. You can always turn a Stream back into a list, map, set or array at any point and take control again.

**Comment by FunnyDevs** [comment]
I hate nested loops and i love declarative code and so i have looked for a library to use on Android without retrolambda(finding yours). I have read a lot of discussions about performance of original Java 8 Stream and so I open this thread to ask you all that about your implementation. 
Thanks a lot for your answer.
